name: CI/CD

on:
  push:
    branches:
      - main # ou a branch que você deseja configurar o CI/CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # ou a versão do Node.js que você deseja usar

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Deploy
        run: |
          # Comandos de implantação da sua aplicação
          # Por exemplo:
          # npm install -g firebase-tools
          # firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
